autogen.sh: do not call `python` just assuming it exists.
On GIMP CI for instance, even though Python 3 was installed in the build
environment, apparently `python` didn't exist in path, hence failing to
create mypaint-brush-settings-gen.h:
> ./autogen.sh: line 238: python: command not found

Instead let's try out several python common binary names (giving
preference to system default `python`, then Python 3, finally Python 2).

Also bad was that the Python error was not fatal, which lead to the
build starting and ultimately failing with:

> ../mypaint-brush-settings.h:22:10: fatal error: mypaint-brush-settings-gen.h: No such file or directory

Therefore make the autogen.sh fail when we fail to run `generate.py`.